name: deploy website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make init
          make build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_CI_CD }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          working-directory: ./public
